Improve UI depends on persona's feedbacks
PlateSwipe/PlateSwipe pull request #186
Opened 2024-11-08 13:34 UTC by AdriB02

# PULL REQUEST TEMPLATE 

This pull request includes several updates to the `SwipePage` feature in the Android sample application. The changes range from adding new UI elements to modifying existing components and improving test coverage.

### UI Enhancements:

* Added a new `ShawRecipeButton` composable to display a button for viewing recipes, including navigation actions and visual enhancements. (`app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt`)
* Introduced gradient background colors for swipe actions using the `getBackgroundColor` function. (`app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt`)
* Updated `PlateSwipeTopBar` to adjust the layout and typography for better visual consistency. (`app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt`) [[1]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9L91-R91) [[2]](diffhunk://#diff-e7eccad8d7f7697fc4aba0798ca200b9207b720391e37d16b2eb0758f6266bd9L103-R103)

### Navigation and Testing:

* Changed the start destination in `NavHost` from `Route.AUTH` to `Route.SWIPE` to improve the user flow. (`app/src/main/java/com/android/sample/MainActivity.kt`)
* Added a new test `shawRecipeButtonIsDisplayed` to verify the display and functionality of the new recipe button. (`app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt`)

### Code Refinements:

* Adjusted swipe threshold calculation to be more responsive by using the correct density value. (`app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt`)
* Improved code readability by reformatting and cleaning up existing code blocks. (`app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt`) [[1]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL187-R203) [[2]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL202-R218) [[3]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL214-R231) [[4]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL253-R271) [[5]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL277-R296) [[6]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL293-R319) [[7]](diffhunk://#diff-75cf2afa31e8e74d24251e864d1f3eb5929ad6f2241939756fac45d863829a4bL318-R340)

### Theming:

* Added new color definitions `redSwipe` and `greenSwipe` for swipe actions. (`app/src/main/java/com/android/sample/ui/theme/Color.kt`)
* Updated the light color scheme to include new container colors for primary and secondary elements. (`app/src/main/java/com/android/sample/ui/theme/Theme.kt`)

## Description
### What has been changed?
### Why was this change made?

## Checklist
- [ ] Tests added.
- [ ] Documentation updated.
- [ ] All CI checks passed.
- [ ] Linked issue/feature (if applicable): #123

2024-11-09 22:03 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/ui/utils/PlateSwipeScaffold.kt
> +              style = MaterialTheme.typography.titleMedium,
Please look at the PR about the theme corrections. I modify the font to be title medium and modify the overall topbar to be more consistent with the figma

2024-11-10 22:22 UTC, CapraSnitzel requested changes
You have done a very good job implementing the different user feedback from last week. In addition, you have more than 80% coverage which is very good.
But before merging your modification with the main, I have a couple of things that need clarification. Once everything is clarified, I will aporove the PR.

2024-11-10 22:22 UTC, CapraSnitzel commented on app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
Quick question which is a little nitpicking. Do you think it could be possible to put the important strings that are used for different test tags and labels in the constants file or not ?

2024-11-10 22:22 UTC, CapraSnitzel commented on app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
It's kinda a little nitpicking, but do you think we could put the strings used for test tags and logs in the constants file or not ? This could help us, in my opinion, change faster a test tag or a log message.

2024-11-11 09:37 UTC, AdriB02 commented on app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
> +    // true).assertIsDisplayed()
Yes, the description was initially used for testing purposes, but with the new button added, it’s no longer needed. I'll go ahead and remove it.

2024-11-11 09:37 UTC, AdriB02 commented on app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
> +  }*/
Same here, this test was initially used for the description, but it's no longer necessary now.

2024-11-11 10:51 UTC, AdriB02 commented on app/src/main/java/com/android/sample/ui/swipePage/SwipePage.kt
Yes, you're right. Thanks !

2024-11-11 10:51 UTC, AdriB02 commented on app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
Done !

2024-11-11 12:05 UTC, CapraSnitzel commented on app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
> +    // true).assertIsDisplayed()
Nice.

2024-11-11 12:06 UTC, CapraSnitzel commented on app/src/androidTest/java/com/android/sample/screen/SwipePageTest.kt
> +  }*/
Ok.

2024-11-11 12:08 UTC, CapraSnitzel commented on app/src/main/java/com/android/sample/ui/authentication/SignInScreen.kt
> +                            Toast.makeText(context, LOGIN_FAILED, Toast.LENGTH_SHORT).show()
Ok, makes more sense to me. Thank you.

2024-11-11 13:53 UTC, CapraSnitzel approved these changes

2024-11-11 13:54 UTC, merged