Feature/total time screen
PlateSwipe/PlateSwipe pull request #245
Opened 2024-11-28 14:28 UTC by 2Fick

# **Description**
- **What has been changed?**  
  A new screen (`TimePickerScreen`) has been added to the recipe creation flow. It allows users to optionally input the total preparation time for their recipe using hour and minute selectors. The selected time is stored in minutes in the `CreateRecipeViewModel` and integrates seamlessly into the existing navigation flow.
![image](https://github.com/user-attachments/assets/25268988-a9c5-4235-b60e-0b71ee9786f0)

- **Why was this change made?**  
  This feature was added to enhance the recipe creation process, enabling users to provide an optional preparation time for better recipe context.

---

# **Code Snippets**

### **`WheelTimePicker`**
This composable uses two `NumberPickerComposable` components to let users select hours and minutes independently. A `Text` component displays a colon (`:`) separator between the hour and minute pickers. The layout is responsive and adapts to various screen widths.

**Example Usage:**
```kotlin
WheelTimePicker(
    selectedHour = 12,
    selectedMinute = 30,
    onTimeSelected = { hour, minute ->
        println("Selected time: $hour:$minute")
    }
)
```

### **`NumberPickerComposable`**
This composable uses `AndroidView` to integrate the native Android `NumberPicker` widget into a Compose layout. It exposes the current value as a semantic property for testing and accessibility. The value is dynamically updated when the `value` parameter changes.

**Example Usage:**
```kotlin
NumberPickerComposable(
    value = 5,
    range = 0..10,
    onValueChange = { newValue ->
        println("New value: $newValue")
    }
)
```

---

# **Problems Encountered**
1. **Initial Attempt Using a Third-Party Library:**  
   Initially tried implementing the picker using [WheelPickerCompose](https://github.com/commandiron/WheelPickerCompose/tree/master). However, this library is under the Apache-2.0 license, which required us to abandon the implementation to avoid licensing conflicts.  

2. **UI Testing with Native `NumberPicker`:**  
   The native Android `NumberPicker` does not expose its values directly to Compose's testing APIs. To resolve this, semantic properties were added to the `NumberPickerComposable` to expose the current value for testing purposes.  

---

# **Checklist**
- [x] Tests added.  
  Unit and E2E tests have been added for `TimePickerScreen` and its integration with the recipe creation flow.

- [x] Documentation updated.  
  Inline comments and descriptions have been added for `TimePickerScreen`, `WheelTimePicker`, and `NumberPickerComposable`.

- [x] All CI checks passed.  
  Verified that all tests, linting, and build processes pass successfully.

- [x] Linked issue/feature:  
  #231

2024-11-28 18:33 UTC, akshire requested changes
Great job on this PR! 🚀 The feature is incredible, and the Recipe Creation screen truly enhances the user experience. 🙌

While testing the UI, I came across a few minor issues that could be addressed to make this even better:

1. Scrolling Issue: When attempting to scroll, the time remains static and doesn't scroll properly. Here's a screen capture for reference:

https://github.com/user-attachments/assets/8dbe3674-e0fd-4bc1-8856-6431b416ec15

2. Time Reset Issue: If I input a time, navigate back, and return to the time screen, the previously entered time gets reset. This disrupts the flow for users. Here's a screen capture of the behavior:

https://github.com/user-attachments/assets/bba1bc56-5d14-4fc6-9413-1c8e6bd71824

3. Progress Bar Consistency: The Progress Bar design on this screen doesn’t match the one on the previous screen. It’s a small detail but maintaining consistency in UI elements helps with a cohesive user experience.

Overall, fantastic work! This feature is shaping up to be a valuable addition. With these tweaks, it will be even more polished. Keep up the great work! 🎉

2024-11-28 18:33 UTC, akshire commented on app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
> +          val totalTimeInMinutes = (hours.intValue * 60) + minutes.intValue
Can you put this value in the `C` file

2024-11-28 18:33 UTC, akshire commented on app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
> +  val initialMinutes = totalMinutes % 60
these constants should be in the `C` file

2024-11-28 18:41 UTC, akshire requested changes
I must say that the code is really clean but I forgot to point you these two constants that are not in the C file.

2024-11-28 18:41 UTC, akshire commented on app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
> +              range = 0..23,
This one should also be in the C file

2024-11-28 18:41 UTC, akshire commented on app/src/main/java/com/android/sample/ui/createRecipe/TimePickerScreen.kt
> +              range = 0..59,
This one should also be in the C file

2024-11-28 20:18 UTC, 2Fick commented
> Great job on this PR! 🚀 The feature is incredible, and the Recipe Creation screen truly enhances the user experience. 🙌
> 
> While testing the UI, I came across a few minor issues that could be addressed to make this even better:
> 
> 1. Scrolling Issue: When attempting to scroll, the time remains static and doesn't scroll properly. Here's a screen capture for reference:
> 
>  Screen_Recording_2024-11-28_180520.mp4 
> 2. Time Reset Issue: If I input a time, navigate back, and return to the time screen, the previously entered time gets reset. This disrupts the flow for users. Here's a screen capture of the behavior:
> 
>  Screen_Recording_2024-11-28_180436.mp4 
> 3. Progress Bar Consistency: The Progress Bar design on this screen doesn’t match the one on the previous screen. It’s a small detail but maintaining consistency in UI elements helps with a cohesive user experience.
> 
> Overall, fantastic work! This feature is shaping up to be a valuable addition. With these tweaks, it will be even more polished. Keep up the great work! 🎉

For the first point, i didnt catch the problem. But 2nd and 3rd point have been resolved.

2024-11-29 06:09 UTC, akshire commented
Regarding the first issue, when watching the video, the scrolling seems quite choppy; it stops after scrolling just three digits. The idea would be to make it smoother and have it stop after more than three digits to bring a sense of fluidity to the scrolling.

2024-11-29 06:10 UTC, akshire approved these changes
Regarding the first issue, when watching the video, the scrolling seems quite choppy; it stops after scrolling just three digits. The idea would be to make it smoother and have it stop after more than three digits to bring a sense of fluidity to the scrolling.

But this can be solved in a future PR, great job! Ready to be merged 🚀

2024-11-29 06:10 UTC, merged