Feature/search categories in create recipes
PlateSwipe/PlateSwipe pull request #295
Opened 2024-12-13 08:06 UTC by RagdollGoDown

# PULL REQUEST TEMPLATE 
## Description
- [ ] What has been changed?
- [ ] Why was this change made?

## Checklist
- [ ] Tests added.
- [ ] Documentation updated.
- [ ] All CI checks passed.
- [ ] Linked issue/feature (if applicable): #123

2024-12-13 17:05 UTC, AdriB02 requested changes
Hi @RagdollGoDown,

Thank you so much for your hard work on this important feature! I really appreciate the time and effort you’ve dedicated over the past few days. I hope you still have a little time to address the few suggestions I’ve shared with you.

Great job, and thank you again!

2024-12-13 17:05 UTC, AdriB02 commented on app/src/test/java/com/android/sample/model/categoryIngredient/CategoryIngredientSearchViewModelTest.kt
Could you please add a test to verify that the factory is created correctly? This would be very useful for ensuring its proper functionality.

2024-12-16 11:15 UTC, RagdollGoDown commented on app/src/test/java/com/android/sample/model/categoryIngredient/CategoryIngredientSearchViewModelTest.kt
of course!

2024-12-16 11:29 UTC, RagdollGoDown commented on app/src/test/java/com/android/sample/model/categoryIngredient/LocalCategoryIngredientRepositoryTest.kt
Unfortunately, I couldn't figure out how to force an IO Exception, but I tested it manually by removing the text file to force one and it just says there aren't any ingredients. So it works it practice. I don't think it's worth the time to figure out how to test this case.

2024-12-16 11:33 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/ui/searchIngredient/SearchIngredientScreen.kt
I didn't notice that! I'll correct it.

2024-12-16 11:34 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/model/categoryIngredient/LocalCategoryIngredientRepository.kt
> +  override fun searchCategory(
Normally you can refer to the interface's documentation. Do you want a method specific doc?

2024-12-16 11:36 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/model/categoryIngredient/CategoryIngredientSearchViewModel.kt
I forgot to write documentation, thanks for pointing it out.

2024-12-16 11:51 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
I can definitely do point 1, but for point 2 I don't think it's worth our time especially considering, we don't store them separately but as just one string.

2024-12-16 12:05 UTC, RagdollGoDown commented on app/src/main/java/com/android/sample/ui/createRecipe/ListIngredientScreen.kt
![image](https://github.com/user-attachments/assets/94cd6914-9ee0-46fd-8a65-da2d2341488d)
Done!

2024-12-16 16:01 UTC, AdriB02 commented on app/src/main/java/com/android/sample/model/categoryIngredient/LocalCategoryIngredientRepository.kt
> +  override fun searchCategory(
I mean a general documentation for the method, explaining what was done.

2024-12-16 16:02 UTC, AdriB02 commented on app/src/test/java/com/android/sample/model/categoryIngredient/CategoryIngredientSearchViewModelTest.kt
Nice !

2024-12-16 16:22 UTC, AdriB02 requested changes
Hi @RagdollGoDown,

First, thank you so much for your changes! They’ve greatly improved both the UX/UI and the overall app experience. 
I have one more suggestion: I think it would be great if you could use the reusable `PlateSwipeButton` utilits instead of the custom button currently defined for this screen. It should be a quick update and would help maintain consistency across the app's design. What do you think?

2024-12-16 22:25 UTC, RagdollGoDown commented
> Hi @RagdollGoDown,
> 
> First, thank you so much for your changes! They’ve greatly improved both the UX/UI and the overall app experience. I have one more suggestion: I think it would be great if you could use the reusable `PlateSwipeButton` utilits instead of the custom button currently defined for this screen. It should be a quick update and would help maintain consistency across the app's design. What do you think?

No problem!

2024-12-17 21:48 UTC, AdriB02 approved these changes
Thank you for your changes! The feature looks excellent, and you've done an outstanding job on this.

If we have time before the deadline, it might be worth updating the quantity input to enforce a specific format. However, as it stands, this looks great, and I’m happy to approve the PR.

2024-12-17 21:48 UTC, merged